In [1]:
import sqlite3 # import the sqlite3 library
import pandas as pd # import the pandas library

In [2]:
conn = sqlite3.connect("champions.db") # create a database
cur = conn.cursor() # create a cursor

In [3]:
df = pd.read_csv("champions.csv") # read a csv file
df.head() # display the first 5 rows

,Champion Name,Role,Base Health,Base Mana,Base Armor,Base Attack Damage,Gold Efficiency
0,Aatrox,Top,580,0,38,60,1.05
1,Ahri,Mid,526,418,21,53,1.02
2,Akali,Mid,575,200,23,62,1.03
3,Alistar,Support,600,350,44,62,1.08
4,Amumu,Jungle,615,285,33,53,1.06

In [4]:
df.to_sql('champs', conn, index=False) # create a table

149

In [6]:
rows = cur.execute("SELECT * FROM champs").fetchall() # select all rows from the table
rows# display the first 5 rows
# rows is a list of tuples
# cur.execute() returns a cursor object
# fetchall() returns a list of tuples

[('Aatrox', 'Top', 580, 0, 38, 60, 1.05),
 ('Ahri', 'Mid', 526, 418, 21, 53, 1.02),
 ('Akali', 'Mid', 575, 200, 23, 62, 1.03),
 ('Alistar', 'Support', 600, 350, 44, 62, 1.08),
 ('Amumu', 'Jungle', 615, 285, 33, 53, 1.06),
 ('Anivia', 'Mid', 480, 495, 21, 51, 1.01),
 ('Annie', 'Mid', 524, 418, 19, 50, 1.0),
 ('Ashe', 'ADC', 570, 280, 26, 59, 1.04),
 ('Aurelion Sol', 'Mid', 575, 350, 19, 57, 1.02),
 ('Azir', 'Mid', 552, 438, 19, 52, 1.01),
 ('Bard', 'Support', 560, 350, 34, 52, 1.05),
 ('Blitzcrank', 'Support', 583, 267, 37, 61, 1.07),
 ('Brand', 'Mid', 590, 469, 22, 57, 1.03),
 ('Braum', 'Support', 540, 311, 47, 55, 1.06),
 ('Caitlyn', 'ADC', 510, 313, 28, 62, 1.05),
 ('Camille', 'Top', 576, 339, 35, 68, 1.06),
 ('Cassiopeia', 'Mid', 560, 800, 18, 53, 1.02),
 ("Cho'Gath", 'Top', 574, 272, 38, 69, 1.08),
 ('Corki', 'ADC', 518, 350, 28, 55, 1.04),
 ('Darius', 'Top', 582, 263, 39, 64, 1.07),
 ('Diana', 'Mid', 570, 375, 31, 57, 1.03),
 ('Dr. Mundo', 'Top', 582, 0, 36, 61, 1.06),
 ('Draven', 'ADC', 574, 360, 29, 61, 1.05),
 ('Ekko', 'Mid', 585, 280, 32, 58, 1.03),
 ('Elise', 'Jungle', 529, 324, 27, 55, 1.03),
 ('Evelynn', 'Jungle', 572, 315, 37, 61, 1.05),
 ('Ezreal', 'ADC', 530, 375, 22, 60, 1.04),
 ('Fiddlesticks', 'Jungle', 580, 500, 34, 55, 1.04),
 ('Fiora', 'Top', 550, 300, 33, 68, 1.06),
 ('Fizz', 'Mid', 570, 317, 22, 58, 1.03),
 ('Galio', 'Mid', 562, 500, 24, 59, 1.04),
 ('Gangplank', 'Top', 540, 280, 35, 64, 1.05),
 ('Garen', 'Top', 620, 0, 36, 66, 1.07),
 ('Gnar', 'Top', 510, 100, 32, 59, 1.03),
 ('Gragas', 'Jungle', 600, 400, 38, 64, 1.07),
 ('Graves', 'Jungle', 555, 322, 33, 66, 1.05),
 ('Hecarim', 'Jungle', 580, 277, 36, 66, 1.06),
 ('Heimerdinger', 'Mid', 488, 385, 19, 55, 1.01),
 ('Illaoi', 'Top', 585, 300, 35, 68, 1.06),
 ('Irelia', 'Top', 590, 350, 36, 63, 1.06),
 ('Ivern', 'Jungle', 585, 450, 27, 50, 1.03),
 ('Janna', 'Support', 500, 350, 28, 46, 1.02),
 ('Jarvan IV', 'Jungle', 570, 300, 34, 64, 1.05),
 ('Jax', 'Top', 592, 338, 36, 68, 1.07),
 ('Jayce', 'Top', 560, 375, 22, 54, 1.02),
 ('Jhin', 'ADC', 585, 300, 24, 59, 1.05),
 ('Jinx', 'ADC', 550, 245, 28, 57, 1.04),
 ("Kai'Sa", 'ADC', 600, 344, 33, 62, 1.06),
 ('Kalista', 'ADC', 534, 250, 21, 69, 1.05),
 ('Karma', 'Support', 534, 374, 26, 53, 1.03),
 ('Karthus', 'Jungle', 528, 467, 21, 45, 1.0),
 ('Kassadin', 'Mid', 576, 400, 19, 59, 1.02),
 ('Katarina', 'Mid', 602, 0, 27, 58, 1.04),
 ('Kayle', 'Top', 600, 330, 26, 50, 1.02),
 ('Kayn', 'Jungle', 585, 410, 38, 68, 1.07),
 ('Kennen', 'Top', 541, 200, 29, 48, 1.01),
 ("Kha'Zix", 'Jungle', 573, 327, 36, 63, 1.05),
 ('Kindred', 'Jungle', 540, 300, 29, 65, 1.05),
 ('Kled', 'Top', 340, 100, 35, 65, 1.04),
 ("Kog'Maw", 'ADC', 534, 325, 24, 57, 1.03),
 ('LeBlanc', 'Mid', 528, 334, 22, 55, 1.02),
 ('Lee Sin', 'Jungle', 575, 200, 33, 70, 1.07),
 ('Leona', 'Support', 576, 302, 47, 60, 1.1),
 ('Lissandra', 'Mid', 550, 475, 22, 53, 1.02),
 ('Lucian', 'ADC', 571, 348, 28, 64, 1.05),
 ('Lulu', 'Support', 525, 350, 29, 47, 1.02),
 ('Lux', 'Mid', 490, 480, 18, 54, 1.01),
 ('Malphite', 'Top', 574, 280, 37, 62, 1.05),
 ('Malzahar', 'Mid', 510, 375, 18, 55, 1.01),
 ('Maokai', 'Top', 565, 375, 39, 64, 1.07),
 ('Master Yi', 'Jungle', 598, 250, 33, 66, 1.06),
 ('Miss Fortune', 'ADC', 570, 300, 28, 52, 1.02),
 ('Mordekaiser', 'Top', 575, 0, 37, 61, 1.06),
 ('Morgana', 'Support', 560, 340, 25, 56, 1.03),
 ('Nami', 'Support', 475, 365, 29, 51, 1.01),
 ('Nasus', 'Top', 561, 325, 34, 67, 1.06),
 ('Nautilus', 'Support', 576, 400, 39, 61, 1.07),
 ('Neeko', 'Mid', 540, 450, 21, 53, 1.02),
 ('Nidalee', 'Jungle', 545, 295, 28, 61, 1.03),
 ('Nocturne', 'Jungle', 585, 275, 38, 62, 1.05),
 ('Nunu & Willump', 'Jungle', 570, 280, 34, 61, 1.04),
 ('Olaf', 'Jungle', 597, 315, 35, 68, 1.07),
 ('Orianna', 'Mid', 530, 418, 17, 49, 1.0),
 ('Ornn', 'Top', 590, 340, 33, 69, 1.06),
 ('Pantheon', 'Top', 580, 317, 40, 64, 1.07),
 ('Poppy', 'Top', 540, 280, 38, 64, 1.06),
 ('Pyke', 'Support', 600, 415, 45, 62, 1.08),
 ('Qiyana', 'Mid', 590, 320, 28, 64, 1.06),
 ('Quinn', 'Top', 532, 268, 28, 59, 1.04),
 ('Rakan', 'Support', 540, 315, 32, 62, 1.05),
 ('Rammus', 'Jungle', 564, 310, 36, 56, 1.04),
 ("Rek'Sai", 'Jungle', 570, 100, 36, 64, 1.05),
 ('Renekton', 'Top', 575, 100, 35, 69, 1.06),
 ('Rengar', 'Jungle', 585, 100, 34, 68, 1.06),
 ('Riven', 'Top', 560, 100, 33, 64, 1.05),
 ('Rumble', 'Top', 589, 100, 30, 61, 1.04),
 ('Samira', 'ADC', 530, 348, 26, 57, 1.03),
 ('Sejuani', 'Jungle', 560, 400, 34, 66, 1.06),
 ('Senna', 'Support', 520, 350, 28, 50, 1.02),
 ('Seraphine', 'Mid', 500, 440, 19, 55, 1.01),
 ('Sett', 'Top', 600, 0, 33, 60, 1.05),
 ('Shaco', 'Jungle', 586, 297, 30, 63, 1.04),
 ('Shen', 'Top', 540, 400, 34, 60, 1.05),
 ('Shyvana', 'Jungle', 595, 100, 38, 66, 1.07),
 ('Singed', 'Top', 580, 330, 34, 62, 1.06),
 ('Sion', 'Top', 545, 330, 32, 68, 1.05),
 ('Sivir', 'ADC', 532, 284, 26, 63, 1.05),
 ('Skarner', 'Jungle', 601, 320, 38, 65, 1.07),
 ('Sona', 'Support', 550, 340, 28, 49, 1.02),
 ('Soraka', 'Support', 535, 425, 32, 50, 1.02),
 ('Swain', 'Mid', 525, 468, 23, 58, 1.03),
 ('Sylas', 'Mid', 525, 400, 27, 61, 1.04),
 ('Syndra', 'Mid', 523, 480, 24, 54, 1.02),
 ('Tahm Kench', 'Support', 600, 325, 47, 56, 1.06),
 ('Taliyah', 'Mid', 532, 450, 20, 58, 1.03),
 ('Talon', 'Mid', 588, 370, 30, 68, 1.06),
 ('Taric', 'Support', 575, 300, 40, 55, 1.05),
 ('Teemo', 'Top', 528, 334, 24, 54, 1.02),
 ('Thresh', 'Support', 560, 273, 28, 56, 1.03),
 ('Tristana', 'ADC', 559, 250, 26, 61, 1.04),
 ('Trundle', 'Jungle', 616, 281, 37, 68, 1.07),
 ('Tryndamere', 'Top', 625, 100, 33, 72, 1.08),
 ('Twisted Fate', 'Mid', 534, 333, 21, 52, 1.01),
 ('Twitch', 'ADC', 612, 287, 27, 59, 1.04),
 ('Udyr', 'Jungle', 594, 271, 34, 66, 1.06),
 ('Urgot', 'Top', 585, 340, 36, 66, 1.06),
 ('Varus', 'ADC', 530, 360, 27, 61, 1.04),
 ('Vayne', 'ADC', 515, 231, 23, 60, 1.03),
 ('Veigar', 'Mid', 505, 490, 23, 52, 1.01),
 ("Vel'Koz", 'Mid', 520, 469, 22, 55, 1.02),
 ('Vi', 'Jungle', 585, 295, 34, 64, 1.05),
 ('Viktor', 'Mid', 530, 405, 23, 53, 1.02),
 ('Vladimir', 'Mid', 537, 100, 23, 55, 1.02),
 ('Volibear', 'Top', 580, 350, 35, 60, 1.05),
 ('Warwick', 'Jungle', 550, 280, 33, 62, 1.05),
 ('Wukong', 'Top', 540, 300, 31, 68, 1.06),
 ('Xayah', 'ADC', 590, 340, 25, 60, 1.05),
 ('Xerath', 'Mid', 526, 480, 21, 55, 1.02),
 ('Xin Zhao', 'Jungle', 590, 273, 35, 66, 1.06),
 ('Yasuo', 'Mid', 490, 100, 30, 60, 1.04),
 ('Yone', 'Mid', 550, 100, 28, 60, 1.04),
 ('Yorick', 'Top', 580, 300, 39, 62, 1.06),
 ('Yuumi', 'Support', 500, 400, 25, 55, 1.02),
 ('Zac', 'Jungle', 615, 0, 33, 60, 1.06),
 ('Zed', 'Mid', 585, 200, 32, 63, 1.05),
 ('Ziggs', 'Mid', 536, 480, 21, 54, 1.02),
 ('Zilean', 'Support', 504, 452, 22, 51, 1.01),
 ('Zoe', 'Mid', 560, 425, 20, 58, 1.02),
 ('Zyra', 'Support', 504, 418, 29, 53, 1.02)]